-- Run in a Snowsight worksheet as ACCOUNTADMIN.
-- Replace YOUR_SNOWFLAKE_USERNAME before running. No password or key belongs in this file.
SET app_user = 'YOUR_SNOWFLAKE_USERNAME';

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS LOYALTY_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Cost-controlled compute for the Loyalty Analytics portfolio application';

CREATE DATABASE IF NOT EXISTS LOYALTY_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS LOYALTY_ANALYTICS.ANALYTICS;
CREATE ROLE IF NOT EXISTS LOYALTY_ANALYTICS_APP;

GRANT USAGE ON WAREHOUSE LOYALTY_ANALYTICS_WH TO ROLE LOYALTY_ANALYTICS_APP;
GRANT USAGE ON DATABASE LOYALTY_ANALYTICS TO ROLE LOYALTY_ANALYTICS_APP;
GRANT USAGE ON SCHEMA LOYALTY_ANALYTICS.ANALYTICS TO ROLE LOYALTY_ANALYTICS_APP;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA LOYALTY_ANALYTICS.ANALYTICS
  TO ROLE LOYALTY_ANALYTICS_APP;
GRANT ROLE LOYALTY_ANALYTICS_APP TO USER IDENTIFIER($app_user);

CREATE TABLE IF NOT EXISTS LOYALTY_ANALYTICS.ANALYTICS.CUSTOMERS (
  ID VARCHAR(36) NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(320) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  LOYALTY_TIER VARCHAR(20) NOT NULL,
  POINTS_BALANCE INTEGER NOT NULL,
  JOIN_DATE DATE NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS LOYALTY_ANALYTICS.ANALYTICS.TRANSACTIONS (
  ID VARCHAR(36) NOT NULL,
  CUSTOMER_ID VARCHAR(36) NOT NULL,
  MERCHANT VARCHAR(150) NOT NULL,
  CATEGORY VARCHAR(100) NOT NULL,
  PURCHASE_AMOUNT NUMBER(12, 2) NOT NULL,
  POINTS_EARNED INTEGER NOT NULL,
  PURCHASE_DATE TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS LOYALTY_ANALYTICS.ANALYTICS.REWARDS (
  ID VARCHAR(36) NOT NULL,
  CUSTOMER_ID VARCHAR(36) NOT NULL,
  REWARD_NAME VARCHAR(150) NOT NULL,
  POINTS_USED INTEGER NOT NULL,
  REDEEMED_AT TIMESTAMP_TZ NOT NULL
);

GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA LOYALTY_ANALYTICS.ANALYTICS
  TO ROLE LOYALTY_ANALYTICS_APP;
